# -*- coding: utf-8 -*-
"""Final uae ecom fraud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dEHB9KzNY0xGWc60S5ujr-WOO9RcPHoP
"""

# ══════════════════════════════════════════════════════════════════════
# CELL 0 — Install Libraries
# ══════════════════════════════════════════════════════════════════════

# !pip install lightgbm xgboost imbalanced-learn --quiet

# lightgbm       → Fast gradient boosting model by Microsoft
# xgboost        → Powerful gradient boosting model, popular in competitions
# imbalanced-learn → Toolkit for handling class imbalance (includes SMOTE)
# --quiet        → Suppress long installation output messages

# CELL 1 — Import Libraries

import pandas as pd
import numpy as np


import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

np.random.seed(42)

# ── Sklearn: Preprocessing & Splitting ────────────────────────────────
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold,
    cross_val_score
)

# ── Sklearn: Models ───────────────────────────────────────────────────
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

# ── Sklearn: Evaluation Metrics ───────────────────────────────────────
from sklearn.metrics import (
    roc_auc_score,
    classification_report,
    f1_score,
    confusion_matrix,
    roc_curve,
    precision_score,
    recall_score
)

# ── SMOTE ─────────────────────────────────────────────────────────────
from imblearn.over_sampling import SMOTE

# ── Boosting Models ───────────────────────────────────────────────────
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

# ── Plot Styling ──────────────────────────────────────────────────────
plt.rcParams.update({
    "figure.facecolor" : "#0f1117",  # Outer figure background color
    "axes.facecolor"   : "#1a1d27",  # Inner plot area background color
    "axes.edgecolor"   : "#2e3248",  # Border color of plot area
    "axes.labelcolor"  : "#c8ccd8",  # Color of axis label text
    "xtick.color"      : "#8b90a0",  # Color of x-axis tick marks
    "ytick.color"      : "#8b90a0",  # Color of y-axis tick marks
    "text.color"       : "#e2e4ee",  # Default text color
    "grid.color"       : "#2e3248",  # Grid line color
    "grid.linewidth"   : 0.6,        # Grid line thickness
    "axes.grid"        : True,       # Show grid by default
    "axes.spines.top"  : False,      # Hide top border
    "axes.spines.right": False,      # Hide right border
    "font.size"        : 11,         # Default font size
})

RED, BLUE, GREEN, AMBER = "#e05252", "#4a90d9", "#4caf7d", "#f0a443"

print("All libraries imported successfully!")

# load Data
from google.colab import files
uploaded = files.upload()

# CELL 2


df_raw = pd.read_csv("uae_ecom_fraud_100k.csv")


df = df_raw.copy()

# ── Display Basic Information ──────────────────────────────────────────
print(f"Dataset shape   : {df.shape}")

print(f"Fraud rate      : {df['is_fraud'].mean():.2%}")

print(f" Null values     : {df.isnull().sum().sum()}")

print(f"\n All columns ({len(df.columns)}):")
print(df.columns.tolist())

print("\n First 5 rows:")
print(df.head())

# CELL 3 — Data Quality Inspection

print("=" * 60)
print("DATA QUALITY REPORT")
print("=" * 60)

# ── 3.1: Target Distribution ──────────────────────────────────────────
print("\n--- Class Distribution (Target Variable: is_fraud) ---")
vc = df["is_fraud"].value_counts()

for label, count in vc.items():
    name = "FRAUD     " if label == 1 else "Legitimate"
    bar  = " " * int(count / len(df) * 40)
    print(f"  {label} ({name}): {count:6,}  {bar}  {count/len(df)*100:.1f}%")


print("\n   CLASS IMBALANCE DETECTED!")
print("  Only ~8% fraud → We need SMOTE to balance before training")
print("  A naive model predicting all-Legitimate gets 92% accuracy")
print("  but catches ZERO fraud — this is why Accuracy is misleading!")

# ── 3.2: Constant or Near-Constant Columns ────────────────────────────
print("\n--- Constant / Near-Constant Columns (will be dropped) ---")
found_const = False
for col in df.columns:
    unique_vals = df[col].nunique()

    if unique_vals <= 1:

        print(f"  CONSTANT      : {col}  (value = {df[col].iloc[0]})")
        found_const = True
    elif df[col].dtype != "object":
        top_freq = df[col].value_counts(normalize=True).iloc[0]

        if top_freq > 0.999:

            print(f"  NEAR-CONSTANT : {col}  ({top_freq:.1%} same value)")
            found_const = True

if not found_const:
    print("  None found ")

# ── 3.3: Impossible / Invalid Values ─────────────────────────────────
print("\n--- Impossible Values ---")
print(f"  user_account_age_days minimum: {df['user_account_age_days'].min()}")


print(f"  card_age_days minimum        : {df['card_age_days'].min()}")

# ── 3.4: Fraud Flags (Leakage Warning) ───────────────────────────────
flag_cols = [c for c in df.columns if "fraud_flag" in c]
print(f"\n--- Fraud Flag Columns ({len(flag_cols)}) — DATA LEAKAGE RISK ---")
for col in flag_cols:
    fraud_overlap = df[df[col] == 1]["is_fraud"].mean()
    print(f"  {col:<35} → fraud rate when flag=1: {fraud_overlap:.1%}")

print("\n   These columns will be DROPPED to prevent leakage!")
print("  The model must learn from raw features, not pre-computed answers")

# ── 3.5: Single-Feature Signal Strength ──────────────────────────────
print("\n--- Single-Feature Signal Strength (AUC) ---")
print("  Healthy range: 0.50 (random) to 0.70 (good signal)")
print("  Above 0.90: SUSPICIOUS — possible leakage\n")
for col in ["ip_risk_score", "user_is_high_risk",
            "user_prev_chargebacks", "amount_aed"]:
    try:
        s = roc_auc_score(df["is_fraud"], df[col])
        s = max(s, 1 - s)

        flag = " ←  SUSPICIOUS" if s > 0.90 else ""
        print(f"  {col:<35}: {s:.4f}{flag}")
    except Exception:
        pass

# ══════════════════════════════════════════════════════════════════════
# CELL 4 — Data Cleaning
# ══════════════════════════════════════════════════════════════════════
# Cleaning order matters:
#   Step A → Handle missing values
#   Step B → Drop identifier columns (IDs, timestamps)
#   Step C → Drop fraud_flag columns (Data Leakage)
#   Step D → Drop constant columns
#   Step E → Fix impossible values
#   Step F → Winsorize (cap) extreme outliers
#   Step G → Encode categorical columns (One-Hot Encoding)

print("=" * 60)
print("DATA CLEANING")
print("=" * 60)

df = df_raw.copy()
df = df.dropna(subset=["is_fraud"]).copy()

df["is_fraud"] = df["is_fraud"].astype(int)


# ── Step A: Handle Missing Values ─────────────────────────────────────
print("\n[Step A] Handling missing values...")
for col in df.columns:
    null_count = df[col].isnull().sum()
    if null_count == 0:
        continue

    if df[col].dtype == "object":

        fill_val = df[col].mode()[0]
        df[col].fillna(fill_val, inplace=True)
        print(f"  {col:<30} → filled {null_count} nulls with mode: '{fill_val}'")
    else:

        fill_val = df[col].median()
        df[col].fillna(fill_val, inplace=True)
        print(f"  {col:<30} → filled {null_count} nulls with median: {fill_val:.2f}")

total_nulls = df.isnull().sum().sum()
print(f"\n  Remaining null values: {total_nulls}{' (none)' if total_nulls == 0 else ''}")

# ── Step B: Drop Identifier & Timestamp Columns ───────────────────────
print("\n[Step B] Dropping identifier and timestamp columns...")


drop_id_cols = [
    "transaction_id", "user_id", "ip_address",
    "data_source", "currency", "timestamp_utc"
]
# Only drop columns that actually exist (avoid errors)
drop_id_cols = [c for c in drop_id_cols if c in df.columns]
df.drop(columns=drop_id_cols, inplace=True, errors="ignore")
print(f"  Dropped: {drop_id_cols}")

# ── Step C: Drop Fraud Flag Columns (Data Leakage) ────────────────────
print("\n[Step C] Dropping fraud_flag columns (Data Leakage)...")

leakage_flags = [
    "fraud_flag_ip",           # IP address flagged as fraudulent
    "fraud_flag_mismatch",     # Shipping/billing city mismatch flagged
    "fraud_flag_velocity",     # High transaction velocity flagged
    "fraud_flag_new_account",  # New account flagged
    "fraud_flag_prev_cb",      # Previous chargebacks flagged
    "fraud_flag_odd_hour"      # Odd hour transaction flagged
]
df.drop(columns=leakage_flags, errors="ignore", inplace=True)
print(f"  Dropped {len(leakage_flags)} fraud_flag columns ")
print("  Model will now learn from RAW signals, not pre-computed answers")

# ── Step D: Drop Constant Columns ─────────────────────────────────────
print("\n[Step D] Dropping constant columns...")
# A column where every row has the same value = ZERO information
# The model cannot learn anything from it
const_cols = [
    c for c in df.columns
    if c != "is_fraud" and df[c].nunique() <= 1
]
if const_cols:
    df.drop(columns=const_cols, inplace=True)
    print(f"  Dropped: {const_cols}")
else:
    print("  No constant columns found ")

# ── Step E: Fix Impossible Values ─────────────────────────────────────
print("\n[Step E] Fixing impossible values...")
# Negative account age is physically impossible
# An account cannot be created in the future
neg_age = (df["user_account_age_days"] < 0).sum()
df["user_account_age_days"] = df["user_account_age_days"].clip(lower=0)
# .clip(lower=0) → Any value below 0 becomes exactly 0
print(f"  user_account_age_days: fixed {neg_age} negative values → set to 0")

neg_card = (df["card_age_days"] < 0).sum()
df["card_age_days"] = df["card_age_days"].clip(lower=0)
print(f"  card_age_days        : fixed {neg_card} negative values → set to 0")

# ── Step F: Winsorize Extreme Outliers ────────────────────────────────
print("\n[Step F] Winsorizing extreme outliers...")

SKIP_WINSORIZE = [
    "is_fraud", "shipping_billing_match", "card_present",
    "card_country_match", "user_is_high_risk", "odd_hour",
    "transactions_last_1h", "transactions_last_24h",
    "user_prev_chargebacks"
]

winsorized = []
for col in df.select_dtypes(include=[np.number]).columns:
    if col in SKIP_WINSORIZE:
        continue  # Skip binary/counter columns

    skewness = abs(df[col].skew())


    if skewness > 3:
        lo = df[col].quantile(0.01)  # 1st percentile (bottom 1%)
        hi = df[col].quantile(0.99)  # 99th percentile (top 1%)
        if lo < hi:
            df[col] = df[col].clip(lo, hi)

            winsorized.append(col)

print(f"  Winsorized {len(winsorized)} columns: {winsorized}")

# ── Step G: One-Hot Encoding ──────────────────────────────────────────
print("\n[Step G] Applying One-Hot Encoding to categorical columns...")


cat_cols = df.select_dtypes("object").columns.tolist()

print(f"  Categorical columns found: {cat_cols}")

if cat_cols:
    df = pd.get_dummies(df, columns=cat_cols, drop_first=True, dtype=int)

    print(f"  One-Hot Encoding applied ")

print(f"\n[Cleaning Complete]")
print(f"  Final shape: {df.shape}")
print(f"  Final columns: {df.columns.tolist()}")
print(f"  Remaining nulls: {df.isnull().sum().sum()}")

# CELL 5 — Exploratory Data Analysis (EDA)


print("Starting EDA...")


fraud = df[df["is_fraud"] == 1]
legit = df[df["is_fraud"] == 0]


fig, axes = plt.subplots(2, 3, figsize=(18, 10))


fig.suptitle(
    "EDA — UAE E-Commerce Fraud Detection Dashboard",
    fontsize=14, fontweight="bold"
)

# ── Plot : Class Distribution ────────────────────────────────────────
counts = df["is_fraud"].value_counts().sort_index()


bars = axes[0, 0].bar(
    ["Legitimate", "Fraud"],
    counts.values,
    color=[BLUE, RED],
    edgecolor="none",
    width=0.5
)


for i, (bar_obj, val) in enumerate(zip(bars, counts.values)):
    axes[0, 0].text(
        bar_obj.get_x() + bar_obj.get_width() / 2,  # x = center of bar
        bar_obj.get_height() + 300,                  # y = above bar
        f"{val:,}\n({val/len(df)*100:.1f}%)",
        ha="center", fontweight="bold", fontsize=10
    )
axes[0, 0].set_title("① Class Distribution\n(8.2% fraud — IMBALANCED)")
axes[0, 0].set_ylabel("Number of Transactions")

# ── Plot : Transaction Amount Distribution ───────────────────────────
axes[0, 1].hist(
    legit["amount_aed"], bins=60,
    color=BLUE, alpha=0.7, label="Legitimate", density=True
)
axes[0, 1].hist(
    fraud["amount_aed"], bins=60,
    color=RED, alpha=0.7, label="Fraud", density=True
)

axes[0, 1].set_yscale("log")

axes[0, 1].set_xlabel("Amount (AED)")
axes[0, 1].set_title("② Transaction Amount\n(fraud skews toward higher amounts)")
axes[0, 1].legend(framealpha=0)

# ── Plot : IP Risk Score Distribution ───────────────────────────────
for subset, label, color in [
    (legit, "Legitimate", BLUE),
    (fraud, "Fraud", RED)
]:
    h, bins = np.histogram(
        subset["ip_risk_score"].dropna(),
        bins=50, density=True
    )

    centers = (bins[:-1] + bins[1:]) / 2

    axes[0, 2].plot(centers, h, color=color, linewidth=2, label=label)
    axes[0, 2].fill_between(centers, h, alpha=0.15, color=color)


axes[0, 2].set_xlabel("IP Risk Score (0-100)")
axes[0, 2].set_title("③ IP Risk Score\n(fraud peaks at higher scores)")
axes[0, 2].legend(framealpha=0)

# ── Plot : Fraud Rate by Hour of Day ────────────────────────────────
hourly_fraud_rate = df.groupby("local_hour")["is_fraud"].mean() * 100


axes[1, 0].fill_between(
    hourly_fraud_rate.index,
    hourly_fraud_rate.values,
    alpha=0.25, color=RED
)
axes[1, 0].plot(
    hourly_fraud_rate.index,
    hourly_fraud_rate.values,
    color=RED, linewidth=2, marker="o", markersize=4
)
# marker="o" → Small circle at each data point (each hour)

axes[1, 0].set_xlabel("Hour of Day (0-23)")
axes[1, 0].set_ylabel("Fraud Rate %")
axes[1, 0].set_title("④ Fraud Rate by Hour\n(night hours = higher fraud)")

# ── Plot : Top Feature Correlations with is_fraud ───────────────────
num_cols_list = df.select_dtypes(include="number").columns.tolist()
correlations = (
    df[num_cols_list].corr()["is_fraud"]

    .drop("is_fraud")
    .abs()
    .sort_values(ascending=False)
    .head(10)
)

axes[1, 1].barh(correlations.index, correlations.values, color=AMBER)

axes[1, 1].set_xlabel("|Correlation with is_fraud|")
axes[1, 1].set_title("⑤ Top 10 Feature Correlations\n(strongest predictors)")

# ── Plot : Fraud Rate by Number of Previous Chargebacks ─────────────
chargeback_fraud = (
    df.groupby("user_prev_chargebacks")["is_fraud"].mean() * 100
)
axes[1, 2].bar(
    chargeback_fraud.index,
    chargeback_fraud.values,
    color=GREEN, edgecolor="none"
)


for x, y in zip(chargeback_fraud.index, chargeback_fraud.values):
    axes[1, 2].text(x, y + 0.3, f"{y:.1f}%", ha="center", fontsize=9)

axes[1, 2].set_xlabel("Number of Previous Chargebacks")
axes[1, 2].set_ylabel("Fraud Rate %")
axes[1, 2].set_title("⑥ Fraud Rate by Chargebacks\n(more history = higher risk)")

plt.tight_layout()


plt.savefig("eda_dashboard.png", dpi=150,
            bbox_inches="tight", facecolor="#0f1117")


plt.show()
print(" EDA Complete! Chart saved as 'eda_dashboard.png'")

# ── Print Key EDA Findings ────────────────────────────────────────────
print("\n Key EDA Findings:")
print(f"  Avg fraud amount  : {fraud['amount_aed'].mean():.2f} AED")
print(f"  Avg legit amount  : {legit['amount_aed'].mean():.2f} AED")
print(f"  Highest fraud hour: {hourly_fraud_rate.idxmax()}:00  "
      f"({hourly_fraud_rate.max():.1f}% fraud rate)")
print(f"  Top predictor     : {correlations.index[0]}  "
      f"(correlation = {correlations.iloc[0]:.3f})")
from sklearn.metrics import roc_auc_score

print("\n Single-feature AUC (pre-cleaning):")

features = ["ip_risk_score", "user_prev_chargebacks",
            "user_is_high_risk", "amount_aed"]

for col in features:
    try:
        s = roc_auc_score(df["is_fraud"], df[col])
        auc_score = max(s, 1 - s)
        print(f"  {col:<30}: {auc_score:.4f}")
    except Exception as e:
        print(f"  {col:<30}: ERROR -> {e}")

print("\n Signals are weak (<0.65) — model must combine them intelligently.")

# CELL 6 — Feature Engineering

print("=" * 60)
print("FEATURE ENGINEERING")
print("=" * 60)

# ── Log Transforms ────────────────────────────────────────────────────

df["amount_log"]   = np.log1p(df["amount_aed"])
df["age_log"]      = np.log1p(df["user_account_age_days"])
df["card_age_log"] = np.log1p(df["card_age_days"])
print(" Log transforms: amount_log, age_log, card_age_log")

# ── Binary Threshold Features ─────────────────────────────────────────

df["is_new_account"] = (df["user_account_age_days"] < 30).astype(int)

df["is_very_new"]    = (df["user_account_age_days"] < 7).astype(int)

df["is_new_card"]    = (df["card_age_days"] < 90).astype(int)
print(" Binary features: is_new_account, is_very_new, is_new_card")

# ── Domain Knowledge Feature ──────────────────────────────────────────

df["new_account_high_value"] = (
    (df["user_account_age_days"] < 30) &
    (df["amount_aed"] > 1000)
).astype(int)

pct = df[df["new_account_high_value"] == 1]["is_fraud"].mean() * 100
print(f" new_account_high_value → fraud rate: {pct:.1f}% ")

# ── Amount per Item ───────────────────────────────────────────────────

df["amount_per_item"] = df["amount_aed"] / df["items_count"].replace(0, 1)
print(" amount_per_item: average cost per item in transaction")

# ── Velocity Ratio ────────────────────────────────────────────────────

df["velocity_ratio"] = (
    (df["transactions_last_1h"]  + 1) /
    (df["transactions_last_24h"] + 1)
)

print(" velocity_ratio: recent vs historical transaction rate")

# ── Interaction Features ──────────────────────────────────────────────


df["ip_x_highuser"]  = df["ip_risk_score"] * df["user_is_high_risk"]
df["ip_x_cb"]        = df["ip_risk_score"] * df["user_prev_chargebacks"]
df["ip_x_new_acc"]   = df["ip_risk_score"] * df["is_new_account"]
df["cb_x_new_acc"]   = df["user_prev_chargebacks"] * df["is_new_account"]
print(" Interaction features: ip_x_highuser, ip_x_cb, ip_x_new_acc, cb_x_new_acc")

# ── Cyclical Hour Encoding ────────────────────────────────────────────

df["hour_sin"] = np.sin(2 * np.pi * df["local_hour"] / 24)
df["hour_cos"] = np.cos(2 * np.pi * df["local_hour"] / 24)

print(" Cyclical encoding: hour_sin, hour_cos")

print(f"\n[Feature Engineering Complete]")
print(f"  Total features created: {df.shape[1] - 1}")
print(f"  DataFrame shape: {df.shape}")

# CELL 7 — Train / Validation / Test Split + Feature Scaling

print("=" * 60)
print("TRAIN / VALIDATION / TEST SPLIT + SCALING")
print("=" * 60)

# ── Define Features and Target ────────────────────────────────────────
EXCLUDE  = ["is_fraud"]
FEATURES = [c for c in df.columns if c not in EXCLUDE]

X = df[FEATURES]
y = df["is_fraud"]

print(f"Feature matrix X: {X.shape}")
print(f"Target vector  y: {y.shape}")
print(f"Features used    : {len(FEATURES)}")

# ── Three-Way Split ───────────────────────────────────────────────────

X_tr, X_temp, y_tr, y_temp = train_test_split(
    X, y,
    test_size    = 0.30,
    stratify     = y,

    random_state = 42
)


X_val, X_te, y_val, y_te = train_test_split(
    X_temp, y_temp,
    test_size    = 0.50,
    stratify     = y_temp,
    random_state = 42
)

print(f"\n  Train size      : {len(X_tr):,}   ({y_tr.mean():.2%} fraud)")
print(f"  Validation size : {len(X_val):,}   ({y_val.mean():.2%} fraud)")
print(f"  Test size       : {len(X_te):,}   ({y_te.mean():.2%} fraud)")
print("  → All sets have approximately the same fraud rate ")

# ── Feature Scaling ───────────────────────────────────────────────────

scaler = StandardScaler()

X_tr_sc = pd.DataFrame(
    scaler.fit_transform(X_tr),
    columns=FEATURES
)

X_val_sc = pd.DataFrame(
    scaler.transform(X_val),
    columns=FEATURES
)


X_te_sc = pd.DataFrame(
    scaler.transform(X_te),
    columns=FEATURES
)

print("\n  Scaling applied (StandardScaler):")
print(f"  amount_aed after scaling:")
print(f"    Train  → mean: {X_tr_sc['amount_aed'].mean():.4f}  "
      f"std: {X_tr_sc['amount_aed'].std():.4f}  ← should be ~0 and ~1")
print(f"    Test   → mean: {X_te_sc['amount_aed'].mean():.4f}  "
      f"(slightly off 0 because different subset)")

# Calculate class imbalance ratio (used in model parameter scale_pos_weight)
RATIO = (y_tr == 0).sum() / (y_tr == 1).sum()

print(f"\n  Class imbalance ratio (scale_pos_weight): {RATIO:.2f}")
print("  → Boosting models will penalize missing fraud 11x more than missing legit")

# CELL 8 — SMOTE: Handle Class Imbalance


print("=" * 60)
print("HANDLING CLASS IMBALANCE WITH SMOTE")
print("=" * 60)

before_counts = dict(pd.Series(y_tr).value_counts())
print(f"\nBefore SMOTE (Train):")
print(f"  Legitimate (0): {before_counts.get(0, 0):,}")
print(f"  Fraud      (1): {before_counts.get(1, 0):,}")
print(f"  Fraud rate    : {y_tr.mean():.2%}")

smote = SMOTE(
    random_state = 42,
    k_neighbors  = 5

)

X_tr_sm, y_tr_sm = smote.fit_resample(X_tr_sc, y_tr)
# fit_resample → Analyzes current distribution, then creates synthetic minority samples
# X_tr_sm → New training features (original + synthetic fraud samples)
# y_tr_sm → New training labels (original + 1s for each synthetic fraud)

after_counts = dict(pd.Series(y_tr_sm).value_counts())
print(f"\nAfter SMOTE (Train):")
print(f"  Legitimate (0): {after_counts.get(0, 0):,}")
print(f"  Fraud      (1): {after_counts.get(1, 0):,}")
print(f"  Fraud rate    : {y_tr_sm.mean():.2%}  ← Now 50/50!")

print(f"\n  SMOTE added {after_counts.get(1,0) - before_counts.get(1,0):,} synthetic fraud samples")
print("   SMOTE applied to Train ONLY — Val and Test remain unmodified")


results = []

# CELL 9 — Baseline Model: Logistic Regression


print("=" * 60)
print("MODEL 1: LOGISTIC REGRESSION (BASELINE)")
print("=" * 60)

lr = LogisticRegression(
    class_weight = "balanced",

    max_iter     = 1000,

    random_state = 42
)


lr.fit(X_tr_sm, y_tr_sm)



lr_val_prob = lr.predict_proba(X_val_sc)[:, 1]
lr_prob     = lr.predict_proba(X_te_sc)[:, 1]

lr_val_auc = roc_auc_score(y_val, lr_val_prob)
lr_auc     = roc_auc_score(y_te, lr_prob)

print(f"\n  Validation AUC : {lr_val_auc:.4f}")
print(f"  Test AUC       : {lr_auc:.4f}  ← reported performance")
print(f"  Gap (overfit)  : {lr_val_auc - lr_auc:.4f}")

results.append({
    "Model"    : "Logistic Regression (baseline)",
    "Val AUC"  : round(lr_val_auc, 4),
    "Test AUC" : round(lr_auc, 4),
    "_prob"    : lr_prob
})

# CELL 10 — Random Forest


print("=" * 60)
print("MODEL 2: RANDOM FOREST")
print("=" * 60)

rf = RandomForestClassifier(
    n_estimators     = 200,

    max_depth        = 10,

    min_samples_leaf = 10,

    class_weight     = "balanced",

    random_state     = 42,
    n_jobs           = -1

)

rf.fit(X_tr_sm, y_tr_sm)

rf_val_prob = rf.predict_proba(X_val_sc)[:, 1]
rf_prob     = rf.predict_proba(X_te_sc)[:, 1]
rf_val_auc  = roc_auc_score(y_val, rf_val_prob)
rf_auc      = roc_auc_score(y_te, rf_prob)

print(f"\n  Validation AUC : {rf_val_auc:.4f}")
print(f"  Test AUC       : {rf_auc:.4f}")
print(f"  Gap (overfit)  : {rf_val_auc - rf_auc:.4f}")

results.append({
    "Model"    : "Random Forest",
    "Val AUC"  : round(rf_val_auc, 4),
    "Test AUC" : round(rf_auc, 4),
    "_prob"    : rf_prob
})

# CELL 11 — LightGBM

print("=" * 60)
print("MODEL 3: LIGHTGBM (FIXED)")
print("=" * 60)

lgbm = LGBMClassifier(
    n_estimators=500,
    learning_rate=0.05,
    num_leaves=31,
    max_depth=6,
    min_child_samples=30,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=RATIO,
    reg_alpha=0.5,
    reg_lambda=2.0,
    random_state=42,
    n_jobs=-1,
    verbose=-1
)


lgbm.fit(
    X_tr, y_tr,
    eval_set=[(X_val, y_val)],
    callbacks=[
        __import__("lightgbm").early_stopping(50, verbose=False),
        __import__("lightgbm").log_evaluation(100),
    ],
)

# ── Predict on Validation and Test ────────────────────────────────────
lgbm_val_prob = lgbm.predict_proba(X_val)[:, 1]
lgbm_prob     = lgbm.predict_proba(X_te)[:, 1]

lgbm_val_auc = roc_auc_score(y_val, lgbm_val_prob)
lgbm_auc     = roc_auc_score(y_te, lgbm_prob)

# ── Cross-Validation on TRAIN only, using SAME LOGIC as final model ──
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
lgbm_cv_aucs = []

for fold, (tri, vli) in enumerate(cv.split(X_tr, y_tr), 1):
    X_fold_tr  = X_tr.iloc[tri]
    y_fold_tr  = y_tr.iloc[tri]
    X_fold_val = X_tr.iloc[vli]
    y_fold_val = y_tr.iloc[vli]

    # Recompute ratio inside each fold for correctness
    fold_ratio = (y_fold_tr == 0).sum() / (y_fold_tr == 1).sum()

    m = LGBMClassifier(
        n_estimators=300,
        learning_rate=0.05,
        num_leaves=31,
        max_depth=6,
        min_child_samples=30,
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight=fold_ratio,
        reg_alpha=0.5,
        reg_lambda=2.0,
        random_state=42,
        verbose=-1,
        n_jobs=-1
    )

    m.fit(X_fold_tr, y_fold_tr)
    fold_prob = m.predict_proba(X_fold_val)[:, 1]
    fold_auc = roc_auc_score(y_fold_val, fold_prob)

    lgbm_cv_aucs.append(fold_auc)
    print(f"  Fold {fold}: AUC = {fold_auc:.4f}")

lgbm_cv_mean = np.mean(lgbm_cv_aucs)
lgbm_cv_std  = np.std(lgbm_cv_aucs)

print(f"\n  Validation AUC : {lgbm_val_auc:.4f}")
print(f"  Test AUC       : {lgbm_auc:.4f}")
print(f"  CV AUC         : {lgbm_cv_mean:.4f} ± {lgbm_cv_std:.4f}")
print(f"  Gap (overfit)  : {lgbm_val_auc - lgbm_auc:.4f}")

results.append({
    "Model"    : "LightGBM (fixed)",
    "Val AUC"  : round(lgbm_val_auc, 4),
    "Test AUC" : round(lgbm_auc, 4),
    "CV AUC"   : f"{lgbm_cv_mean:.4f} ± {lgbm_cv_std:.4f}",
    "_prob"    : lgbm_prob
})

# CELL 12 — XGBoost




print("=" * 60)
print("MODEL 4: XGBOOST (FIXED)")
print("=" * 60)
xgb = XGBClassifier(
    max_depth=4,
    learning_rate=0.03,
    n_estimators=250,
    scale_pos_weight=RATIO,
    subsample=0.7,
    colsample_bytree=0.7,
    min_child_weight=15,
    gamma=1.0,
    reg_alpha=1.0,
    reg_lambda=3.0,
    random_state=42,
    n_jobs=-1,
    verbosity=0,
    eval_metric="auc"
)

# ── Train FINAL model on ORIGINAL train data (NO SMOTE, NO SCALING) ──
xgb.fit(
    X_tr, y_tr,
    eval_set=[(X_val, y_val)],
    verbose=False
)

# ── Predict on Validation and Test ────────────────────────────────────
xgb_val_prob = xgb.predict_proba(X_val)[:, 1]
xgb_prob     = xgb.predict_proba(X_te)[:, 1]

xgb_val_auc = roc_auc_score(y_val, xgb_val_prob)
xgb_auc     = roc_auc_score(y_te, xgb_prob)

# ── Overfitting Check ─────────────────────────────────────────────────
# IMPORTANT: compute Train AUC on ORIGINAL train data
tr_auc = roc_auc_score(y_tr, xgb.predict_proba(X_tr)[:, 1])
gap    = tr_auc - xgb_auc

status = (
    " OK — good generalization" if gap < 0.05 else
    " ACCEPTABLE" if gap < 0.10 else
    " OVERFIT — model memorized training data"
)

print(f"\n  Train AUC      : {tr_auc:.4f}")
print(f"  Validation AUC : {xgb_val_auc:.4f}")
print(f"  Test AUC       : {xgb_auc:.4f}")
print(f"  Gap            : {gap:.4f}  {status}")

# ── Cross-Validation on TRAIN only, using SAME LOGIC as final model ──
xgb_cv_aucs = []

for fold, (tri, vli) in enumerate(cv.split(X_tr, y_tr), 1):
    X_fold_tr  = X_tr.iloc[tri]
    y_fold_tr  = y_tr.iloc[tri]
    X_fold_val = X_tr.iloc[vli]
    y_fold_val = y_tr.iloc[vli]

    # Recompute ratio inside each fold for correctness
    fold_ratio = (y_fold_tr == 0).sum() / (y_fold_tr == 1).sum()

    m = XGBClassifier(
        max_depth=5,
        learning_rate=0.05,
        n_estimators=300,
        scale_pos_weight=fold_ratio,
        subsample=0.8,
        colsample_bytree=0.8,
        min_child_weight=10,
        reg_alpha=0.5,
        reg_lambda=2.0,
        random_state=42,
        n_jobs=-1,
        verbosity=0,
        eval_metric="auc"
    )

    m.fit(X_fold_tr, y_fold_tr, verbose=False)
    fold_prob = m.predict_proba(X_fold_val)[:, 1]
    fold_auc = roc_auc_score(y_fold_val, fold_prob)

    xgb_cv_aucs.append(fold_auc)
    print(f"  Fold {fold}: AUC = {fold_auc:.4f}")

xgb_cv_mean = np.mean(xgb_cv_aucs)
xgb_cv_std  = np.std(xgb_cv_aucs)

print(f"\n  CV AUC : {xgb_cv_mean:.4f} ± {xgb_cv_std:.4f}")
print("  Low std confirms model stability across different data subsets")

results.append({
    "Model"    : "XGBoost (fixed)",
    "Val AUC"  : round(xgb_val_auc, 4),
    "Test AUC" : round(xgb_auc, 4),
    "CV AUC"   : f"{xgb_cv_mean:.4f} ± {xgb_cv_std:.4f}",
    "_prob"    : xgb_prob
})

# CELL 13 — Model Comparison Table


print("=" * 60)
print("MODEL COMPARISON")
print("=" * 60)

df_results = pd.DataFrame([
    {k: v for k, v in r.items() if k != "_prob"}
    for r in results
])
# Remove the "_prob" key (private, used for plotting)
# Create a clean DataFrame for display

print(df_results.to_string(index=False))
# to_string(index=False) → Print without row numbers

# Identify the best model
best_result = max(results, key=lambda r: r["Test AUC"])
best_prob   = best_result["_prob"]
print(f"\n BEST MODEL: {best_result['Model']}")
print(f"   Test AUC : {best_result['Test AUC']:.4f}")
print(f"   Val AUC  : {best_result['Val AUC']:.4f}")

# CELL 14 — Threshold Tuning + Final Evaluation

print("=" * 60)
print("THRESHOLD TUNING + FINAL EVALUATION")
print("=" * 60)

# ── Tune on Validation Set ────────────────────────────────────────────
print("\n[Step 1] Finding optimal threshold on VALIDATION set...")

thresholds = np.arange(0.05, 0.70, 0.01)


f1_scores_val = [
    f1_score(y_val, (xgb_val_prob >= t).astype(int))
    for t in thresholds
]


best_t = thresholds[np.argmax(f1_scores_val)]


print(f"  Optimal threshold found: {best_t:.2f}")
print(f"  Best F1 on Validation  : {max(f1_scores_val):.4f}")
print(f"  (Tuned on Validation — Test not touched yet)")

# ── Apply ONCE to Test Set ────────────────────────────────────────────
print(f"\n[Step 2] Applying threshold {best_t:.2f} to TEST SET (once only)...")

y_pred = (xgb_prob >= best_t).astype(int)

print(f"\n  === FINAL TEST SET PERFORMANCE ===")
print(classification_report(
    y_te, y_pred,
    target_names=["Legitimate", "Fraud"]
))


print(f"  Test AUC  : {xgb_auc:.4f}")
print(f"  Precision : {precision_score(y_te, y_pred):.4f}")
print(f"  Recall    : {recall_score(y_te, y_pred):.4f}  ← MOST IMPORTANT!")
print(f"  F1-Score  : {f1_score(y_te, y_pred):.4f}")


caught = int(recall_score(y_te, y_pred) * y_te.sum())
missed = int(y_te.sum() - caught)
print(f"\n  Business Impact:")
print(f"  Total actual fraud in Test   : {y_te.sum()}")
print(f"  Fraud cases CAUGHT           : {caught}  ")
print(f"  Fraud cases MISSED           : {missed}  ")

# CELL 15 — Data Leakage Verification


print("=" * 60)
print("LEAKAGE VERIFICATION")
print("=" * 60)
print("Checking each feature's individual AUC on Test set...")
print("Threshold: AUC > 0.90 = SUSPICIOUS (possible data leakage)\n")

leak_found = False
suspicious_cols = []

for col in X_te.columns:
    try:
        col_auc = roc_auc_score(y_te, X_te[col])
        col_auc = max(col_auc, 1 - col_auc)


        if col_auc > 0.90:
            print(f"   SUSPICIOUS: {col:<35} AUC = {col_auc:.4f}")
            suspicious_cols.append(col)
            leak_found = True
        elif col_auc > 0.75:
            print(f"    NOTABLE  : {col:<35} AUC = {col_auc:.4f}")
    except Exception:
        pass

if not leak_found:
    print("   No leakage detected — all features within acceptable AUC range")
else:
    print(f"\n  Action needed: Review {suspicious_cols}")
    print("  Consider dropping these features before production deployment")

# CELL 16 — Final Visualization


fig, axes = plt.subplots(1, 3, figsize=(20, 6))
fig.suptitle(
    "Final Evaluation — UAE E-Commerce Fraud Detection",
    fontsize=14, fontweight="bold"
)

# ── ROC Curves: All Models ────────────────────────────────────────────

model_plot_data = [
    ("Logistic Regression", lr_prob,   AMBER),
    ("Random Forest",       rf_prob,   GREEN),
    ("LightGBM",            lgbm_prob, BLUE),
    ("XGBoost ",           xgb_prob,  RED),
]

for name, prob, color in model_plot_data:
    auc_val = roc_auc_score(y_te, prob)
    fpr, tpr, _ = roc_curve(y_te, prob)

    axes[0].plot(
        fpr, tpr, linewidth=2, color=color,
        label=f"{name} (AUC={auc_val:.4f})"
    )

axes[0].plot([0, 1], [0, 1], "--", color="#8b90a0", linewidth=1)


axes[0].set_xlabel("False Positive Rate (legitimate flagged as fraud)")
axes[0].set_ylabel("True Positive Rate (actual fraud caught)")
axes[0].set_title("ROC Curves — All Models")
axes[0].legend(framealpha=0, fontsize=9)

# ── Confusion Matrix ──────────────────────────────────────────────────


cm = confusion_matrix(y_te, y_pred)
sns.heatmap(
    cm, annot=True, fmt="d",

    cmap="Blues",
    xticklabels=["Predicted: Legit", "Predicted: Fraud"],
    yticklabels=["Actual: Legit", "Actual: Fraud"],
    ax=axes[1],
    linewidths=0.5
)
axes[1].set_title(
    f"Confusion Matrix — XGBoost\n"
    f"(threshold = {best_t:.2f})",
    fontweight="bold"
)

# ── Feature Importance ────────────────────────────────────────────────


fi_df = (
    pd.DataFrame({
        "feature"    : FEATURES,
        "importance" : xgb.feature_importances_

    })
    .sort_values("importance", ascending=False)
    .head(15)

)


fi_colors = []
for feat in fi_df["feature"]:
    if "ip" in feat or "risk" in feat:
        fi_colors.append(RED)
    elif "amount" in feat:
        fi_colors.append(BLUE)
    elif "cb" in feat or "chargeback" in feat:
        fi_colors.append(GREEN)
    else:
        fi_colors.append(AMBER)

axes[2].barh(
    fi_df["feature"][::-1],
    fi_df["importance"][::-1],
    color=fi_colors[::-1],
    edgecolor="none"
)
axes[2].set_xlabel("Feature Importance Score")
axes[2].set_title("Top 15 Most Important Features\n(XGBoost)", fontweight="bold")

plt.tight_layout()
plt.savefig("final_evaluation.png", dpi=150,
            bbox_inches="tight", facecolor="#0f1117")
plt.show()
print(" Final evaluation charts saved as 'final_evaluation.png'")

# Advanced Model Visualization Dashboard


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import roc_curve, roc_auc_score, confusion_matrix, precision_score, recall_score, f1_score

# ── Build clean results table ─────────────────────────────────────────
viz_results = pd.DataFrame([
    {
        "Model": r["Model"],
        "Validation AUC": r["Val AUC"],
        "Test AUC": r["Test AUC"]
    }
    for r in results
])

viz_results["Gap"] = (viz_results["Validation AUC"] - viz_results["Test AUC"]).abs()
viz_results = viz_results.sort_values("Test AUC", ascending=False).reset_index(drop=True)

print("Model comparison table:")
display(viz_results)

# ── Figure Layout ─────────────────────────────────────────────────────
fig = plt.figure(figsize=(22, 14))
gs = fig.add_gridspec(3, 2, height_ratios=[1.0, 1.2, 1.2], hspace=0.35, wspace=0.22)

fig.suptitle("Fraud Detection Models — Performance Dashboard", fontsize=18, fontweight="bold")

# ══════════════════════════════════════════════════════════════════════
# 1) Test AUC Comparison
# ══════════════════════════════════════════════════════════════════════
ax1 = fig.add_subplot(gs[0, 0])

bars = ax1.bar(
    viz_results["Model"],
    viz_results["Test AUC"],
    edgecolor="black"
)

ax1.set_title("1. Test AUC by Model", fontweight="bold")
ax1.set_ylabel("Test AUC")
ax1.set_ylim(0, 1)

for bar, val in zip(bars, viz_results["Test AUC"]):
    ax1.text(
        bar.get_x() + bar.get_width()/2,
        val + 0.015,
        f"{val:.4f}",
        ha="center",
        fontweight="bold"
    )

plt.setp(ax1.get_xticklabels(), rotation=15, ha="right")

# ══════════════════════════════════════════════════════════════════════
# 2) Validation vs Test AUC
# ══════════════════════════════════════════════════════════════════════
ax2 = fig.add_subplot(gs[0, 1])

x = np.arange(len(viz_results))
width = 0.36

bars1 = ax2.bar(x - width/2, viz_results["Validation AUC"], width, label="Validation AUC", edgecolor="black")
bars2 = ax2.bar(x + width/2, viz_results["Test AUC"], width, label="Test AUC", edgecolor="black")

ax2.set_title("2. Validation vs Test AUC", fontweight="bold")
ax2.set_ylabel("AUC")
ax2.set_ylim(0, 1)
ax2.set_xticks(x)
ax2.set_xticklabels(viz_results["Model"], rotation=15, ha="right")
ax2.legend()

for group in [bars1, bars2]:
    for bar in group:
        h = bar.get_height()
        ax2.text(bar.get_x() + bar.get_width()/2, h + 0.012, f"{h:.4f}", ha="center", fontsize=9)

# ══════════════════════════════════════════════════════════════════════
# 3) ROC Curves
# ══════════════════════════════════════════════════════════════════════
ax3 = fig.add_subplot(gs[1, 0])

model_plot_data = [
    ("Logistic Regression", lr_prob),
    ("Random Forest", rf_prob),
    ("LightGBM", lgbm_prob),
    ("XGBoost", xgb_prob),
]

for name, prob in model_plot_data:
    fpr, tpr, _ = roc_curve(y_te, prob)
    auc_val = roc_auc_score(y_te, prob)
    ax3.plot(fpr, tpr, linewidth=2, label=f"{name} (AUC={auc_val:.4f})")

ax3.plot([0, 1], [0, 1], "--", color="gray")
ax3.set_title("3. ROC Curves — All Models", fontweight="bold")
ax3.set_xlabel("False Positive Rate")
ax3.set_ylabel("True Positive Rate")
ax3.legend(fontsize=9)

# ══════════════════════════════════════════════════════════════════════
# 4) Confusion Matrix for Best Model
# ══════════════════════════════════════════════════════════════════════
ax4 = fig.add_subplot(gs[1, 1])

cm = confusion_matrix(y_te, y_pred)
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    cbar=False,
    ax=ax4,
    xticklabels=["Pred Legit", "Pred Fraud"],
    yticklabels=["Actual Legit", "Actual Fraud"],
    linewidths=1
)

ax4.set_title(f"4. Confusion Matrix — XGBoost (threshold={best_t:.2f})", fontweight="bold")

# ══════════════════════════════════════════════════════════════════════
# 5) Top Feature Importance
# ══════════════════════════════════════════════════════════════════════
ax5 = fig.add_subplot(gs[2, 0])

fi_df = pd.DataFrame({
    "Feature": FEATURES,
    "Importance": xgb.feature_importances_
}).sort_values("Importance", ascending=False).head(15)

ax5.barh(fi_df["Feature"][::-1], fi_df["Importance"][::-1], edgecolor="black")
ax5.set_title("5. Top 15 Feature Importance — XGBoost", fontweight="bold")
ax5.set_xlabel("Importance Score")

# ══════════════════════════════════════════════════════════════════════
# 6) Final Metrics Summary
# ══════════════════════════════════════════════════════════════════════
ax6 = fig.add_subplot(gs[2, 1])
ax6.axis("off")

precision = precision_score(y_te, y_pred)
recall = recall_score(y_te, y_pred)
f1 = f1_score(y_te, y_pred)
auc = roc_auc_score(y_te, xgb_prob)

best_model_name = viz_results.iloc[0]["Model"]
best_model_auc = viz_results.iloc[0]["Test AUC"]

summary_text = f"""
Best Model: {best_model_name}
Best Test AUC: {best_model_auc:.4f}

Final Deployed Model:
XGBoost

Threshold:
{best_t:.2f}

Precision:
{precision:.4f}

Recall:
{recall:.4f}

F1-score:
{f1:.4f}

ROC-AUC:
{auc:.4f}
"""

ax6.text(
    0.03, 0.97, summary_text,
    va="top", fontsize=13,
    bbox=dict(boxstyle="round,pad=0.6", facecolor="black", edgecolor="black")
)
ax6.set_title("6. Executive Metrics Summary", fontweight="bold")

plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.savefig("advanced_model_dashboard.png", dpi=200, bbox_inches="tight")
plt.show()

print("Saved as: advanced_model_dashboard.png")

# CELL 17 — Cross-Validation Stability Report

print("=" * 60)
print("CROSS-VALIDATION STABILITY — XGBOOST (5-FOLD ON TRAIN)")
print("=" * 60)
print("(FIX: CV on Train only — original notebook used all data including Test)")
print()

for i, score in enumerate(xgb_cv_aucs, 1):
    bar = " " * int(score * 50)  # Visual bar proportional to AUC
    print(f"  Fold {i}: {score:.4f}  {bar}")

print(f"\n  Mean AUC   : {xgb_cv_mean:.4f}")
print(f"  Std Dev    : {xgb_cv_std:.4f}")

cv_status = " STABLE" if xgb_cv_std < 0.01 else \
            "  MODERATE VARIANCE" if xgb_cv_std < 0.02 else \
            " UNSTABLE — model is sensitive to data split"
print(f"  Status     : {cv_status}")

if xgb_cv_std < 0.01:
    print("\n  Low standard deviation confirms:")
    print("  → Model is consistent across different training subsets")
    print("  → Performance is not due to luck or a favorable split")
    print("  → Safe to deploy with confidence")

# CELL 18 — Conclusions & Business Recommendations


print("=" * 60)
print("CONCLUSIONS & BUSINESS RECOMMENDATIONS")
print("=" * 60)

print(f"""
PROBLEM
  Detect fraudulent e-commerce transactions in the UAE
  Dataset: 100,000 transactions with {df['is_fraud'].mean():.2%} fraud rate
  Challenge: Severe class imbalance — naive model catches zero fraud

FIXES APPLIED VS ORIGINAL NOTEBOOK
  ① Removed Signal Fix cell → was corrupting original data values
  ② One-Hot Encoding instead of Label Encoding → no false ordering
  ③ SMOTE on Train only → evaluation uses real data distribution
  ④ CV on Train only → no test set leakage in cross-validation
  ⑤ Threshold tuning on Validation → Test used exactly once
  ⑥ Conservative hyperparameters → reduced severe overfitting
  ⑦ Added Random Forest → better model comparison

MODEL PERFORMANCE SUMMARY
  Logistic Regression : {lr_auc:.4f} AUC (baseline)
  Random Forest       : {rf_auc:.4f} AUC
  LightGBM            : {lgbm_auc:.4f} AUC
  XGBoost ★ Champion  : {xgb_auc:.4f} AUC

KEY FINDINGS FROM EDA
  Top fraud predictors: user_prev_chargebacks, ip_risk_score, user_is_high_risk
  Night hours (00:00-06:00) → elevated fraud rate
  New accounts (<30 days) + large amounts → classic fraud pattern
  All payment methods have similar fraud rates (payment type alone is weak signal)

BUSINESS DEPLOYMENT RECOMMENDATION
  Model: XGBoost with probability threshold = {best_t:.2f}

  Decision logic:
    prob >= {best_t:.2f}  →  FLAG for manual review
    prob <  {best_t:.2f}  →  Approve automatically

  Performance at threshold {best_t:.2f}:
    Fraud Recall    : {recall_score(y_te, y_pred):.1%}  (of fraud cases, we catch this many)
    Fraud Precision : {precision_score(y_te, y_pred):.1%}  (of flagged, this many are real fraud)
    F1-Score        : {f1_score(y_te, y_pred):.4f}

NEXT STEPS
  → Retrain monthly as fraud patterns evolve
  → Add real-time velocity features via Kafka / Spark streaming
  → Build a Streamlit dashboard for the fraud operations team
  → Implement human-in-the-loop: use reviewed cases as training data
  → A/B test different thresholds to balance fraud loss vs customer friction
  → Consider separate models for high-value vs low-value transactions
""")